/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviegui;
import java.awt.Color;
import java.util.ArrayList;
import java.sql.SQLException;
import java.util.HashMap;
/**
 *
 * @author MD
 */
public class Seats extends javax.swing.JFrame {
    public static ArrayList<MovieSeats> seatNumber=new ArrayList<MovieSeats>();
    private ArrayList<Integer> seatBooked=new ArrayList<Integer>();
    static Ticket ticket;
    HashMap<Integer, javax.swing.JToggleButton> ButtonList = new HashMap<Integer, javax.swing.JToggleButton>();
    /**
     * Creates new form Seats
     */
    public Seats() {
        initComponents();
        TestConnection sqlCon =new TestConnection();
        ButtonList.put(1, Seat1);
        ButtonList.put(2, Seat2);
        ButtonList.put(3, Seat3);
        ButtonList.put(4, Seat4);
        ButtonList.put(5, Seat5);
        ButtonList.put(6, Seat6);
        ButtonList.put(7, Seat7);
        ButtonList.put(8, Seat8);
        ButtonList.put(9, Seat9);
        ButtonList.put(10, Seat10);
        ButtonList.put(11, Seat11);
        ButtonList.put(12, Seat12);
        ButtonList.put(13, Seat13);
        ButtonList.put(14, Seat14);
        ButtonList.put(15, Seat15);
        ButtonList.put(16, Seat16);
        ButtonList.put(17, Seat17);
        ButtonList.put(18, Seat18);
        
        
        
        try{
        seatBooked=sqlCon.getBookedSeats(MovieObject.showTime,MainGUI.movie.getOriginal_title(),MovieObject.showdate);
        for(Integer x : seatBooked){
           ButtonList.get(x).setBackground(new java.awt.Color(204, 255, 204));
            ButtonList.get(x).setEnabled(false);
        }
        
            
        }
        catch (SQLException e) {
      System.out.println("Connection fail");
      
    }
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Seat6 = new javax.swing.JToggleButton();
        Seat5 = new javax.swing.JToggleButton();
        Seat18 = new javax.swing.JToggleButton();
        Seat10 = new javax.swing.JToggleButton();
        Seat2 = new javax.swing.JToggleButton();
        Seat1 = new javax.swing.JToggleButton();
        Seat4 = new javax.swing.JToggleButton();
        Seat3 = new javax.swing.JToggleButton();
        Seat14 = new javax.swing.JToggleButton();
        Seat13 = new javax.swing.JToggleButton();
        Seat12 = new javax.swing.JToggleButton();
        Seat11 = new javax.swing.JToggleButton();
        Seat17 = new javax.swing.JToggleButton();
        Seat9 = new javax.swing.JToggleButton();
        Seat15 = new javax.swing.JToggleButton();
        Seat7 = new javax.swing.JToggleButton();
        Seat16 = new javax.swing.JToggleButton();
        Seat8 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Screen");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 720, 70));

        Seat6.setBackground(new java.awt.Color(204, 255, 204));
        Seat6.setText("6");
        Seat6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat6StateChanged(evt);
            }
        });
        Seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat6ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, -1));

        Seat5.setBackground(new java.awt.Color(204, 255, 204));
        Seat5.setText("5");
        Seat5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat5StateChanged(evt);
            }
        });
        Seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat5ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, -1));

        Seat18.setBackground(new java.awt.Color(204, 255, 204));
        Seat18.setText("18");
        Seat18.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat18StateChanged(evt);
            }
        });
        Seat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat18ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 100, -1));

        Seat10.setBackground(new java.awt.Color(255, 0, 255));
        Seat10.setText("10");
        Seat10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat10StateChanged(evt);
            }
        });
        Seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat10ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, -1));

        Seat2.setBackground(new java.awt.Color(255, 0, 255));
        Seat2.setText("2");
        Seat2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat2StateChanged(evt);
            }
        });
        Seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat2ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, -1));

        Seat1.setBackground(new java.awt.Color(204, 255, 204));
        Seat1.setText("1");
        Seat1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat1StateChanged(evt);
            }
        });
        Seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat1ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        Seat4.setBackground(new java.awt.Color(204, 255, 204));
        Seat4.setText("4");
        Seat4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat4StateChanged(evt);
            }
        });
        Seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat4ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, -1));

        Seat3.setBackground(new java.awt.Color(204, 255, 204));
        Seat3.setText("3");
        Seat3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat3StateChanged(evt);
            }
        });
        Seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat3ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));

        Seat14.setBackground(new java.awt.Color(204, 255, 204));
        Seat14.setText("14");
        Seat14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat14StateChanged(evt);
            }
        });
        Seat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat14ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 100, -1));

        Seat13.setBackground(new java.awt.Color(204, 255, 204));
        Seat13.setText("13");
        Seat13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat13StateChanged(evt);
            }
        });
        Seat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat13ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 100, -1));

        Seat12.setBackground(new java.awt.Color(204, 255, 204));
        Seat12.setText("12");
        Seat12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat12StateChanged(evt);
            }
        });
        Seat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat12ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 100, -1));

        Seat11.setBackground(new java.awt.Color(204, 255, 204));
        Seat11.setText("11");
        Seat11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat11StateChanged(evt);
            }
        });
        Seat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat11ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 100, -1));

        Seat17.setBackground(new java.awt.Color(204, 255, 204));
        Seat17.setText("17");
        Seat17.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat17StateChanged(evt);
            }
        });
        Seat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat17ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 100, -1));

        Seat9.setBackground(new java.awt.Color(204, 255, 204));
        Seat9.setText("9");
        Seat9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat9StateChanged(evt);
            }
        });
        Seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat9ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, -1));

        Seat15.setBackground(new java.awt.Color(204, 255, 204));
        Seat15.setText("15");
        Seat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat15ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 100, -1));

        Seat7.setBackground(new java.awt.Color(204, 255, 204));
        Seat7.setText("7");
        Seat7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat7StateChanged(evt);
            }
        });
        Seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat7ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 110, -1));

        Seat16.setBackground(new java.awt.Color(204, 255, 204));
        Seat16.setText("16");
        Seat16.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat16StateChanged(evt);
            }
        });
        Seat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat16ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 100, -1));

        Seat8.setBackground(new java.awt.Color(204, 255, 204));
        Seat8.setText("8");
        Seat8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Seat8StateChanged(evt);
            }
        });
        Seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seat8ActionPerformed(evt);
            }
        });
        getContentPane().add(Seat8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 110, -1));

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat18ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(18);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat18ActionPerformed

    private void Seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat1ActionPerformed
        MovieSeats seat=new MovieSeats(1);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat1ActionPerformed

    private void Seat1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat1StateChanged
        if(Seat1.isSelected()){     
        Seat1.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat1.setBackground(new java.awt.Color(204, 255, 204));
        }// TODO add your handling code here:
    }//GEN-LAST:event_Seat1StateChanged

    private void Seat2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat2StateChanged
        if(Seat2.isSelected()&& User_login.currentUser.getStatus()){     
        Seat2.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat2.setBackground(new java.awt.Color(128, 0, 128));
        }
    }//GEN-LAST:event_Seat2StateChanged

    private void Seat3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat3StateChanged
         if(Seat3.isSelected()){     
        Seat3.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat3.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat3StateChanged

    private void Seat4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat4StateChanged
        if(Seat4.isSelected()){     
        Seat4.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat4.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat4StateChanged

    private void Seat5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat5StateChanged
        if(Seat5.isSelected()){     
        Seat5.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat5.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat5StateChanged

    private void Seat6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat6StateChanged
                if(Seat6.isSelected()){     
        Seat6.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat6.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat6StateChanged

    private void Seat10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat10StateChanged
                if(Seat10.isSelected()&& User_login.currentUser.getStatus()){     
        Seat10.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat10.setBackground(new java.awt.Color(128, 0, 128));
        }
    }//GEN-LAST:event_Seat10StateChanged

    private void Seat18StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat18StateChanged
               if(Seat18.isSelected()){     
        Seat18.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat18.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat18StateChanged

    private void Seat11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat11StateChanged
          if(Seat11.isSelected()){     
        Seat11.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat11.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat11StateChanged

    private void Seat12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat12StateChanged
        if(Seat12.isSelected()){     
        Seat12.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat12.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat12StateChanged

    private void Seat13StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat13StateChanged
        if(Seat13.isSelected()){     
        Seat13.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat13.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat13StateChanged

    private void Seat14StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat14StateChanged
        if(Seat14.isSelected()){     
        Seat14.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat14.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat14StateChanged

    private void Seat7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat7StateChanged
        if(Seat7.isSelected()){     
        Seat7.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat7.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat7StateChanged

    private void Seat8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat8StateChanged
        if(Seat8.isSelected()){     
        Seat8.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat8.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat8StateChanged

    private void Seat16StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat16StateChanged
       if(Seat16.isSelected()){     
        Seat16.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat16.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat16StateChanged

    private void Seat17StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat17StateChanged
       if(Seat17.isSelected()){     
        Seat17.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat17.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat17StateChanged

    private void Seat9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Seat9StateChanged
        if(Seat9.isSelected()){     
        Seat9.setBackground(new java.awt.Color(255, 0, 0));}
        else{
            Seat9.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_Seat9StateChanged

    private void Seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat2ActionPerformed
        // TODO add your handling code here:
        if (User_login.currentUser.getStatus()){
        MovieSeats seat=new MovieSeats(2);
        seatNumber.add(seat);
        }
    }//GEN-LAST:event_Seat2ActionPerformed

    private void Seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat10ActionPerformed
        // TODO add your handling code here:
        if (User_login.currentUser.getStatus()){
        MovieSeats seat=new MovieSeats(10);
        seatNumber.add(seat);
        }
    }//GEN-LAST:event_Seat10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        seatNumber.clear();
        MainGUI x = new MainGUI();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!(seatNumber.isEmpty())){
         
         
        Payment x = new Payment();
        x.setVisible(true);
        dispose();
        }
        else{
            jLabel2.setText("Please Book a Seat to Proceed");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat4ActionPerformed
        // TODO add your handling code here:
        
        MovieSeats seat=new MovieSeats(4);
        seatNumber.add(seat);;
    }//GEN-LAST:event_Seat4ActionPerformed

    private void Seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat3ActionPerformed
        // TODO add your handling code here:
        
        MovieSeats seat=new MovieSeats(3);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat3ActionPerformed

    private void Seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat5ActionPerformed
        // TODO add your handling code here:
        
        MovieSeats seat=new MovieSeats(5);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat5ActionPerformed

    private void Seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat6ActionPerformed
        // TODO add your handling code here:
        
        MovieSeats seat=new MovieSeats(6);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat6ActionPerformed

    private void Seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat7ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(7);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat7ActionPerformed

    private void Seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat8ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(8);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat8ActionPerformed

    private void Seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat9ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(9);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat9ActionPerformed

    private void Seat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat11ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(11);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat11ActionPerformed

    private void Seat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat12ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(12);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat12ActionPerformed

    private void Seat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat13ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(13);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat13ActionPerformed

    private void Seat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat14ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(14);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat14ActionPerformed

    private void Seat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat15ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(15);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat15ActionPerformed

    private void Seat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat16ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(16);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat16ActionPerformed

    private void Seat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seat17ActionPerformed
        // TODO add your handling code here:
        MovieSeats seat=new MovieSeats(17);
        seatNumber.add(seat);
    }//GEN-LAST:event_Seat17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seats().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Seat1;
    private javax.swing.JToggleButton Seat10;
    private javax.swing.JToggleButton Seat11;
    private javax.swing.JToggleButton Seat12;
    private javax.swing.JToggleButton Seat13;
    private javax.swing.JToggleButton Seat14;
    private javax.swing.JToggleButton Seat15;
    private javax.swing.JToggleButton Seat16;
    private javax.swing.JToggleButton Seat17;
    private javax.swing.JToggleButton Seat18;
    private javax.swing.JToggleButton Seat2;
    private javax.swing.JToggleButton Seat3;
    private javax.swing.JToggleButton Seat4;
    private javax.swing.JToggleButton Seat5;
    private javax.swing.JToggleButton Seat6;
    private javax.swing.JToggleButton Seat7;
    private javax.swing.JToggleButton Seat8;
    private javax.swing.JToggleButton Seat9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
